// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class CoubMedia {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CoubMedia {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCoubMedia(bb:flatbuffers.ByteBuffer, obj?:CoubMedia):CoubMedia {
  return (obj || new CoubMedia()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCoubMedia(bb:flatbuffers.ByteBuffer, obj?:CoubMedia):CoubMedia {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CoubMedia()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

audioMimeType():string|null
audioMimeType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
audioMimeType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

audioData(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

audioDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

audioDataArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

videoMimeType():string|null
videoMimeType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
videoMimeType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

videoData(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

videoDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

videoDataArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startCoubMedia(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addAudioMimeType(builder:flatbuffers.Builder, audioMimeTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, audioMimeTypeOffset, 0);
}

static addAudioData(builder:flatbuffers.Builder, audioDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, audioDataOffset, 0);
}

static createAudioDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startAudioDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addVideoMimeType(builder:flatbuffers.Builder, videoMimeTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, videoMimeTypeOffset, 0);
}

static addVideoData(builder:flatbuffers.Builder, videoDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, videoDataOffset, 0);
}

static createVideoDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startVideoDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endCoubMedia(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCoubMedia(builder:flatbuffers.Builder, audioMimeTypeOffset:flatbuffers.Offset, audioDataOffset:flatbuffers.Offset, videoMimeTypeOffset:flatbuffers.Offset, videoDataOffset:flatbuffers.Offset):flatbuffers.Offset {
  CoubMedia.startCoubMedia(builder);
  CoubMedia.addAudioMimeType(builder, audioMimeTypeOffset);
  CoubMedia.addAudioData(builder, audioDataOffset);
  CoubMedia.addVideoMimeType(builder, videoMimeTypeOffset);
  CoubMedia.addVideoData(builder, videoDataOffset);
  return CoubMedia.endCoubMedia(builder);
}
}
