// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CoubMedia } from '../../coub-replay/serialization/coub-media.js';
import { CoubMetadata } from '../../coub-replay/serialization/coub-metadata.js';


export class Coub {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Coub {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCoub(bb:flatbuffers.ByteBuffer, obj?:Coub):Coub {
  return (obj || new Coub()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCoub(bb:flatbuffers.ByteBuffer, obj?:Coub):Coub {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Coub()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static bufferHasIdentifier(bb:flatbuffers.ByteBuffer):boolean {
  return bb.__has_identifier('COUB');
}

metadata(obj?:CoubMetadata):CoubMetadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new CoubMetadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

media(obj?:CoubMedia):CoubMedia|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new CoubMedia()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startCoub(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMetadata(builder:flatbuffers.Builder, metadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, metadataOffset, 0);
}

static addMedia(builder:flatbuffers.Builder, mediaOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, mediaOffset, 0);
}

static endCoub(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishCoubBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'COUB');
}

static finishSizePrefixedCoubBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'COUB', true);
}

}
