// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class CoubMetadata {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CoubMetadata {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCoubMetadata(bb:flatbuffers.ByteBuffer, obj?:CoubMetadata):CoubMetadata {
  return (obj || new CoubMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCoubMetadata(bb:flatbuffers.ByteBuffer, obj?:CoubMetadata):CoubMetadata {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CoubMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

permalink():string|null
permalink(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
permalink(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

title():string|null
title(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
title(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

author():string|null
author(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
author(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

createdAt():bigint|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : null;
}

updatedAt():bigint|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : null;
}

static startCoubMetadata(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addPermalink(builder:flatbuffers.Builder, permalinkOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, permalinkOffset, 0);
}

static addTitle(builder:flatbuffers.Builder, titleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, titleOffset, 0);
}

static addAuthor(builder:flatbuffers.Builder, authorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, authorOffset, 0);
}

static addCreatedAt(builder:flatbuffers.Builder, createdAt:bigint) {
  builder.addFieldInt64(3, createdAt, null);
}

static addUpdatedAt(builder:flatbuffers.Builder, updatedAt:bigint) {
  builder.addFieldInt64(4, updatedAt, null);
}

static endCoubMetadata(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // permalink
  return offset;
}

static createCoubMetadata(builder:flatbuffers.Builder, permalinkOffset:flatbuffers.Offset, titleOffset:flatbuffers.Offset, authorOffset:flatbuffers.Offset, createdAt:bigint|null, updatedAt:bigint|null):flatbuffers.Offset {
  CoubMetadata.startCoubMetadata(builder);
  CoubMetadata.addPermalink(builder, permalinkOffset);
  CoubMetadata.addTitle(builder, titleOffset);
  CoubMetadata.addAuthor(builder, authorOffset);
  if (createdAt !== null)
    CoubMetadata.addCreatedAt(builder, createdAt);
  if (updatedAt !== null)
    CoubMetadata.addUpdatedAt(builder, updatedAt);
  return CoubMetadata.endCoubMetadata(builder);
}
}
